language: go
go:
  - "1.11"

git:
  depth: 10

sudo: required

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install node -y
  - go get -u -v github.com/gohugoio/hugo
  - npm install -g gulp

install:
  - npm install

script:
  - gulp sass

before_deploy:
  - gulp sass && hugo

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    on:
      branch: master
