baseURL: "https://compbiocore.github.io/refchef-view/"
languageCode: "en-us"
title: "RefChef"
publishDir: docs

# Site params
params:
    description: "List of Genome References available on URSA Stronghold and CCV's Oscar."
    email: cbc-help@brown.edu
    copyright: Computational Biology Core - Data Science Practice - Brown University
    organization:
        main: Computational Biology Core
        parent: Center for Computational Biology of Human Disease
    address: 3 Davol Sq., Providence RI 02903
    brown_url: "https://www.brown.edu"
    cbc_url: "https://cbc.brown.edu"


    menu:
      cbc:
        - name: About
          url: https://cbc.brown.edu/about/
        - name: Support
          url: https://cbc.brown.edu/support/
        - name: Services
          url: https://cbc.brown.edu/services/
        - name: Resources
          url: https://cbc.brown.edu/resources/
        - name: Blog
          url: https://cbc.brown.edu/blog/

    footer:
      secondcolumn:
      - "**Acknowledgements**"
      - Research reported on this website is supported by an Institutional Development
        Award (IDeA) from the National Institute of General Medical Sciences of the
        National Institutes of Health under grant number P20GM109035.
