baseURL: "http://example.org/"
languageCode: "en-us"
title: "RefChef"

# Site params
params:
    description: "List of Genome References available on URSA Stronghold and CCV's Oscar."
    email: cbc-help@brown.edu
    copyright: Computational Biology Core - Data Science Practice - Brown University
    organization:
        main: Computational Biology Core
        parent: Center for Computation and Visualization
    address: 3 Davol Sq., Providence RI 02903
    brown_url: "https://www.brown.edu"
    cbc_url: "https://cbc.brown.edu"
