baseURL: "https://compbiocore.github.io/refchef-view/"
languageCode: "en-us"
title: "RefChef"
publishDir: docs

# Site params
params:
    description: "List of Genome References available on URSA Stronghold and CCV's Oscar."
    email: cbc-help@brown.edu
    copyright: Computational Biology Core - Data Science Practice - Brown University
    organization:
        main: Computational Biology Core
        parent: Center for Computation and Visualization
    address: 3 Davol Sq., Providence RI 02903
    brown_url: "https://www.brown.edu"
    cbc_url: "https://cbc.brown.edu"
    
    menu:
      cbc:
        - name: Support
          url: http://cbc.brown.edu/support/index.html
        - name: Services
          url: http://cbc.brown.edu/services/index.html
        - name: Resources
          url: http://cbc.brown.edu/resources/index.html
        - name: About
          url: http://cbc.brown.edu/about/index.html
